### ISSUE TITLE
화면 전환 할 때마다 메모리 증가 이슈

### ISSUE THREAD

**Issue by zekexros** [zeke-iOS/SideDishWithRx#21]
# 1. 시연 영상

<img width="50%" src="https://user-images.githubusercontent.com/42647277/141464955-fa25c3bd-9660-42b0-b258-9756a75bcd62.gif"/>

<br/><br/>

# 2. 메모리 크기

<img width="276" alt="스크린샷 2021-11-12 오후 8 59 24" src="https://user-images.githubusercontent.com/42647277/141465567-3292c445-e775-48e6-9a86-5f38f1df0483.png">
<img width="279" alt="스크린샷 2021-11-12 오후 8 59 36" src="https://user-images.githubusercontent.com/42647277/141465577-3bcbf4fe-9ba5-426f-8bcc-7cea6055b923.png">
<img width="281" alt="스크린샷 2021-11-12 오후 8 59 48" src="https://user-images.githubusercontent.com/42647277/141465587-e79a1fd4-5a58-43d9-8502-fb05b34dadae.png">

- 위 영상처럼 화면전환을 반복하면 아래와 같이 메모리가 점차 증가합니다.

<br/><br/>

# 3. Instrument 사용하여 Memory Leak 분석
<img width="880" alt="스크린샷 2021-11-12 오후 10 48 45" src="https://user-images.githubusercontent.com/42647277/141477323-f8cf507b-b583-48c3-a31a-72b2cef11a16.png">

- Instrument를 통해 Memory Leak 2개를 확인하였습니다.

**Comment by zeke-iOS** [comment]
### DetailViewController의 인스턴스가 해제되지 않는 것 같아 새로운 타입을 생성하고 타입 프로퍼티를 통해 사실여부를 확인하였습니다.
```swift
class ViewControllerBox {
    static var box = [UIViewController?]()
}
```

<br/><br/>

<img width="558" alt="스크린샷 2021-11-12 오후 11 49 53" src="https://user-images.githubusercontent.com/42647277/141485926-4d4fe45a-9aca-4af6-b118-982644745bbf.png">

- 결과는 의심대로 DetailViewController의 인스턴스가 해제되지 않고 계속하여 쌓이고 있었습니다.
- 시나리오는 MainViewController에서 DetailViewController로 전환하고 다시 MainViewController로 되돌아갔다가 DetailViewController로 다시 전환한 후 MainViewController로 되돌아 왔을 때 Box에 담긴 모습을 캡쳐

**Comment by zekexros** [comment]
## 변경 전
```swift
viewModel.output.detailImages
            .observe(on: MainScheduler.instance)
            .compactMap { UIImage(data: $0) }
            .map { image -> UIImageView in
                let ratio = image.size.width / image.size.height
                let imageView = UIImageView(image: image)
                imageView.snp.makeConstraints { view in
                    view.width.equalTo(imageView.snp.height).multipliedBy(ratio)
                }
                return imageView
            }
            .bind(onNext: { imageView in
                self.detailScrollView.addSubviewInDetailSectionStackView(view: imageView)
            })
            .disposed(by: rx.disposeBag)
```

## 변경 후
```swift
viewModel.output.detailImages
            .observe(on: MainScheduler.instance)
            .compactMap { UIImage(data: $0) }
            .map { image -> UIImageView in
                let ratio = image.size.width / image.size.height
                let imageView = UIImageView(image: image)
                imageView.snp.makeConstraints { view in
                    view.width.equalTo(imageView.snp.height).multipliedBy(ratio)
                }
                return imageView
            }
            .bind(onNext: { [weak self] imageView in
                self?.detailScrollView.addSubviewInDetailSectionStackView(view: imageView)
            })
            .disposed(by: rx.disposeBag)
```

- DetailViewController의 인스턴스가 해제되지 않는 것 같습니다. 따라서 DetailViewController의 deinit함수를 통해 실제 인스턴스가 해제되지 않는지 확인하였습니다.
- 결과는 역시 화면전환 할때마다 DetailViewController의 인스턴스가 해제되지 않고 계속하여 쌓이고 있었습니다.
- bind의 onNext클로저에서 캡쳐 리스트가 사용되지 않아 DetailViewController의 reference count가 증가하여 메모리에서 해제되지 않았습니다(강한 순환 참조 발생). 따라서 캡쳐 리스트를 사용하여 강한 순환 참조를 피하여 문제를 해결하였습니다.
