### ISSUE TITLE
table view cell을 선택시 화면전환이 안되는 현상

### ISSUE THREAD

**Issue by zekexros** [zeke-iOS/SideDishWithRx#8]
![Simulator Screen Recording - iPhone 12 - 2021-08-05 at 17 43 22](https://user-images.githubusercontent.com/42647277/128322235-d736d260-1e87-4308-a7b2-b2d5b13c3a87.gif)

1. 위 영상과 같이 cell을 눌러 detail scene으로 화면전환 후, main scene으로 되돌아 옵니다. 
<br/>

2. 그리고 다시 cell을 눌러보지만 detail scene으로 화면전환이 되지 않습니다.
<br/>

3. 예상되는 이유로는 coordinator객체에서 close transition을 정의하지 않고 호출하지도 않아 currentVC가 바뀌지 않기 때문에 되돌아 온 후 다시 화면전환을 시도해도 이뤄지지 않습니다.
<br/>

4. 구체적으로 설명하자면 셀을 눌러 화면전환 하게되면 coordinator객체의 currentVC는 detail scene입니다. 이후 back버튼을 눌러 main scene으로 돌아오지만 coordinator의 currentVC는 아직 여전히 detail scene입니다.
<br/>

5. detail scene에서 main scene으로 되돌아올 때, currentVC는 여전히 detail scene이고 navigation 스택에서 detail scene이 사라지게 때문에 detail scene의 navigation controller에 대한 참조를 잃게 됩니다.
<br/>

6. 따라서 되돌아 온 이후 다시 cell을 클릭하여 화면전환을 하려고 하면 navigation controller의 옵셔널 처리 로직에 따라 error이벤트를 전달하게 됩니다.
<img width="1370" alt="스크린샷 2021-08-05 오후 6 10 23" src="https://user-images.githubusercontent.com/42647277/128325287-1fb9f545-da45-4e10-86a9-fabbd597fb25.png">
<img width="670" alt="스크린샷 2021-08-05 오후 6 10 48" src="https://user-images.githubusercontent.com/42647277/128325305-ec47d7fd-8140-4759-b7fa-be8169d4dd02.png">
<br/>

**Comment by zeke-iOS** [comment]
## 디버깅을 하던 과정 중 겪었던 또다른 문제
1. detail scene에서 분명 navigation controller를 참조하고 있는데 bar button item은 계속해서 nil로 나오는 상황
<br/>

2. `navigationItem`의 `backBarbuttonItem`을 참조하였는데 뷰 디버깅을 통해 알아보니 `navigationItem`이 아닌 `navigationBar`의 `backItem.backBarButtonItem`을 참조해야 한다.
<img width="429" alt="스크린샷 2021-08-05 오후 9 02 01" src="https://user-images.githubusercontent.com/42647277/128346608-0c4a73d9-11fe-419f-835b-282f62930798.png">

**Comment by zekexros** [comment]
새로 생성한 navigation bar button item을 navigation controller의 navigation item으로 지정해준 후 action을 바인딩하였지만 action은 호출되지 않았다.
디버깅 하는 과정에서 깨닫게 된 몇가지는 다음과 같다.
- navigation item의 back button은 현재 화면이 아닌 이전 화면에서 지정해주어야 한다.
- navigation item의 back button의 action은 항상 기본 action만 호출된다. (따라서 pop action을 바인딩하여도 호출되지 않는다. 이 부분을 깨닫는데 가장 많이 시간이 소요되었다. 그럴거면 back button의 action을 쓰지 못하게끔 막아줬어야 하지 않나...)

따라서 navigation item의 hides back button을 통해 숨겨주고 left bar button item에 새로 생성한 bar button item을 지정해주니 정상적으로 동작하였다.
```swift
func bindViewModel() {
        var backButton = UIBarButtonItem(title: "뒤로", style: .done, target: nil, action: nil)
        backButton.rx.action = viewModel.popAction
        navigationItem.hidesBackButton = true
        navigationItem.leftBarButtonItem = backButton
    }
```
